### ISSUE TITLE
Ask: Run boring generators without added to Gemfile

### ISSUE THREAD

**Issue by luathn** [abhaynikam/boring_generators#12]
Hi. I see we can install boring generators like this:
```
$ gem install boring_generators
```
But I can't find how I can run it. Like: `boring generate boring:pry:install`.
Can you show me?

**Comment by abhaynikam** [comment]
@luathn Currently, we can run the generator without adding them to the Gemfile. I am working on getting the CLI ready in PR: #2. Once the PR is merged we can easily use the generator with just `boring generate boring:pry:install`

For now, please add the generator in the development group and run a `bundle install`. After that, `rails generate boring:pry:install` should do the trick. Hope that helps 😊 

The pry generator has some mostly used config `.pryrc` which might be helpful. Please feel free to comment back if you have  more feedback or feature request. Thanks you 🎉

**Comment by luathn** [comment]
@abhaynikam Oh. PR #2 is exactly what I need. I thought if you didn't implement this, I'll do.
I look forward to that feature. I'll help you to add more lib to generators/boring :metal:

**Comment by abhaynikam** [comment]
@luathn Thank you. Would really appreciate any help I get making progress with the gem ❤️❤️

Please feel free to take up anything you like.

**Comment by abhaynikam** [comment]
Resolved in PR: #19
