### ISSUE TITLE
Bootstrap 5 does not use jquery

### ISSUE THREAD

**Issue by yshmarov** [abhaynikam/boring_generators#46]
Bootstrap 4 needs jquery and changes to env.js. Bootstrap 5 does not. This 
https://github.com/abhaynikam/boring_generators/blob/main/lib/generators/boring/bootstrap/install/install_generator.rb
can be updated.

My guide to installing bootstrap 5:
console:
```
yarn add bootstrap@next
yarn add @popperjs/core
```
application.js
```
import 'bootstrap/dist/js/bootstrap'
import "bootstrap/dist/css/bootstrap";
```
done :)

Unless you have a more correct approach

**Comment by deepakmahakale** [comment]
https://github.com/abhaynikam/boring_generators/blob/main/lib/generators/boring/bootstrap/install/install_generator.rb#L11

Need to change this if bootstrap is 5 & above 

```ruby
yarn add bootstrap@next jquery @popperjs/core
```
