### ISSUE TITLE
should call `@popperjs/core`

### ISSUE THREAD

**Issue by yshmarov** [abhaynikam/boring_generators#56]
https://github.com/abhaynikam/boring_generators/blob/0df20a34db020a51f332e47f40ff8505bfb26710/lib/generators/boring/bootstrap/install/install_generator.rb#L11

I got this message :)
<img width="493" alt="Screenshot 2021-12-09 at 21 38 05" src="https://user-images.githubusercontent.com/13472945/145472103-83090f9e-fc28-4687-a20b-88d9374eebfe.png">

and indeed, we should use the `core` thingy in order for it to work now:

<img width="898" alt="Screenshot 2021-12-09 at 21 39 40" src="https://user-images.githubusercontent.com/13472945/145472270-b6f0e5bb-fcbd-4f5d-ae9f-268cd9ab3ef2.png">

**Comment by pipolo23** [comment]
I solved with yarn add @popperjs/core, 
I tried not npn install @popperjs/core but it did not work

**Comment by abhaynikam** [comment]
Closed by #61
