### ISSUE TITLE
using with rails 7 without webpacker

### ISSUE THREAD

**Issue by anilaeus** [abhaynikam/boring_generators#90]
Thank you for this amazing project however are there any workaround for rails 7?

**Comment by coolprobn** [comment]
@anilonrails Did you get into some errors? If you can post those then it will be easier to debug and provide you with  guidance in the right direction.

I am using this project in Rails 7 and newer versions already and generators work as intended. If you are getting issues then it most probably might be for a specific generator with some issues we have not caught.
